# Generated by Django 4.2.1 on 2023-09-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=150)),
                ('primary_color', models.CharField(max_length=6)),
                ('second_color', models.CharField(max_length=6)),
                ('thrid_color', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='images/')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.project')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.work')),
            ],
        ),
    ]
