# Generated by Django 4.2.1 on 2023-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='skills',
        ),
        migrations.AddField(
            model_name='work',
            name='skills',
            field=models.ManyToManyField(to='resume.skill'),
        ),
    ]
