# Generated by Django 4.2.1 on 2023-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_work_skills_work_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='Product Manager', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='role',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='works',
        ),
        migrations.AddField(
            model_name='role',
            name='projects',
            field=models.ManyToManyField(to='resume.project'),
        ),
        migrations.AddField(
            model_name='role',
            name='works',
            field=models.ManyToManyField(to='resume.work'),
        ),
    ]
