# Generated by Django 4.2.1 on 2023-09-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_role_name_remove_role_projects_remove_role_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abb',
            field=models.CharField(choices=[('pm', 'pm'), ('sd', 'sd'), ('da', 'da'), ('et', 'et'), ('ma', 'ma')], default='pm', max_length=2),
            preserve_default=False,
        ),
    ]
