# Generated by Django 4.2.1 on 2023-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_project_abb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='abb',
        ),
        migrations.AddField(
            model_name='role',
            name='abb',
            field=models.CharField(choices=[('pm', 'pm'), ('sd', 'sd'), ('da', 'da'), ('et', 'et'), ('ma', 'ma')], default='pm', max_length=2),
            preserve_default=False,
        ),
    ]
