# Generated by Django 4.2.1 on 2023-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_work_end_year_work_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='primary_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='role',
            name='second_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='role',
            name='thrid_color',
            field=models.CharField(max_length=7),
        ),
    ]
