# Generated by Django 4.2.1 on 2023-09-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_role_primary_color_alter_role_second_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='primary_color',
            new_name='first_color',
        ),
    ]
