# Generated by Django 4.2.1 on 2023-09-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_rename_thrid_color_role_third_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='abb',
            new_name='abbreviation',
        ),
    ]
